### PR TITLE
Made a fake sw_vers for some build to pass

### PR DESCRIPTION
**Pull request by wavewave**
I made a fake `sw_vers`. The result is based on my system OS X 10.9. New files are located in `pkgs/os-specific/darwin/sw_vers` and I added `sw_vers` in `darwin` in `all-packages.nix` like `c++filt`

### CODE REVIEW

**Comment by wavewave** [comment]
The fake `sw_vers` shows the following results. 
```
$ result/bin/sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.4
BuildVersion:   13E28
$ result/bin/sw_vers -ProductName
Mac OS X
$ result/bin/sw_vers -ProductVersion
10.9.4
$ result/bin/sw_vers -BuildVersion 
13E28
```

**Comment by wavewave** [comment]
`sw_vers -productVersion` is correct, not `sw_vers -ProductVersion` (capital letter). fixed it.

**Comment by shlevy** [comment]
For pure-darwin we're trying to support 10.7, right?

**Comment by wavewave** [comment]
I was not sure about the exact policy and after all, the string was from the result of my own machine (the only data point for me). Can anyone provide a realistic result from `sw_vers` on 10.7 (especially build version)?

**Comment by copumpkin** [comment]
@jwiegley has a 10.7 VM. Mind giving us the output of `sw_vers` on there? :smile:

**Comment by jwiegley** [comment]
@copumpkin It is:

```
ProductName:   Mac OS X
ProductVersion: 10.7.5
BuildVersion:   11G63
```

**Comment by wavewave** [comment]
@jwiegley @copumpkin @shlevy : changed to 10.7.5. Thanks.

**Comment by copumpkin** [comment]
Thanks!

**Comment by wmertens** [comment]
Are there things that will refuse to build/build sub-optimally when targeting 10.7.5 for 10.10 systems?

**Comment by shlevy** [comment]
AFAIK the only significant known loss by not targeting `10.10` is not having some of the fancy new `*_at` syscall variants, but those were only introduced in `10.10` anyway and I don't think any packages have broken as a result.

My thought here is that we should support as far back as is convenient (IIRC @jwiegley found some fundamental problem with going back to 10.6?) and then don't worry about it until/unless a concrete issue arises, at which point we can consider the tradeoffs.

**Comment by wmertens** [comment]
Works for me.

**Comment by copumpkin** [comment]
If I remember correctly, 10.7 introduced proper thread-local storage. I think there have been a few improvements to the mach-o format since then, but most changes are at the system API level. At some point I'll map out the various changes. 

Also not clear how many of those linker-level changes apply to us if we try to run a newer dyld (compiled ourselves) on an older kernel.

**Pull request merged**
