### PR TITLE
Allow emacs to build on darwin

### PR DESCRIPTION
**Pull request by kulakowski**

### CODE REVIEW

**Comment by copumpkin** [comment]
Thanks! I'm not an emacs expert, but how does this differ from `emacs24Macport`? @jwiegley might also be interested!

**Comment by kulakowski** [comment]
I wasn't aware of the macport versions, or if they should be preferred.

I personally have no need for all the OS X integration it provides, but the build works just fine!

**Comment by copumpkin** [comment]
Yeah, I was using `emacs24Macport` as my emacs test case and it's been working for a while, but I'm very happy to get a more generic emacs working too. All you had to do was move some of the substitution further up the file? Funny!

**Comment by copumpkin** [comment]
Now that I look at it more carefully, I don't actually understand why your change fixes it! Care to explain what's going on?

**Comment by kulakowski** [comment]
All non-linux values of $system return early in that case statement.

**Comment by copumpkin** [comment]
Oh, of course, silly me! Okay, I'll merge away :smile: thanks again!

**Comment by jwiegley** [comment]
I'm really not interested in Cocoa Emacs, but having it build is, of course, to be desired.

**Comment by copumpkin** [comment]
Oh, so this version is the cocoa one? I always assumed the Macport one was! Goes to show how much I know about emacs :smile:

**Comment by jwiegley** [comment]
"Mac port" Emacs is a back-port of GNU Emacs onto Carbon.  The main feature that it has over the Cocoa port is much lower latency when communicating with asynchronous processes.  Cocoa Emacs can get bad enough in that respect that on-the-fly spellchecking is simply unusable.

**Pull request merged**
